language: go
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install

install:
  - go get github.com/golang/lint/golint
  - go get -u github.com/golang/dep/...

before_script:
  - $GOPATH/bin/dep ensure -v --vendor-only
  - go vet ./metrics.go
  - go vet ./events.go
  - go vet ./tools/sa-bench
  - golint . | xargs -r false
  - pip install --user ansible
  - mkdir ${TRAVIS_BUILD_DIR}/qpid-proton-build
  - ansible-playbook --extra-vars "workdir=${TRAVIS_BUILD_DIR}/qpid-proton-build" -c local -i localhost, ci/travis-setup-amqp.yaml

script:
  - go build -o metric-listener metrics.go
  - go build -o event-listener events.go
  - go build -o tools/sa-bench/sa-bench tools/sa-bench/main.go
